/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.yann.servlet.rssreader;

import br.com.yann.servlet.rssreader.model.Rss;
import br.com.yann.servlet.rssreader.util.RssConvertor;

public class App {

   public static void main(String[] args)  {

    String url = "http://blogs.bing.com/webmaster/feed/";

    RssConvertor convertor = new RssConvertor();
    Rss rss = convertor.getRss(url);

    System.out.println(rss.getLink());
    System.out.println(rss.getTitle());
    System.out.println(rss.getDescription());
  }
}